server:
  port: 9090
  error:
    whitelabel:
      enabled: false

cors:
  allowed-origins: http://localhost:8080

pagination:
  default-page-size: 10
  max-page-size: 50

spring:
  application:
    name: breakable_toy_1
